# Generated by Django 5.0.4 on 2024-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(height_field=400, upload_to='images', width_field=300),
        ),
    ]
