# Generated by Django 5.0.6 on 2024-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('emailid', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=10)),
                ('date1', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
                ('contact', models.CharField(max_length=15)),
                ('emailid', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=50)),
                ('joindate', models.CharField(max_length=50)),
                ('expiredate', models.CharField(max_length=50)),
                ('initialamount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
                ('is_staff', models.BooleanField(default=True)),
                ('contact', models.CharField(max_length=15)),
                ('emailid', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('experience', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
